---
title: "index"
author: "Walid Hedidar"
date: "4/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## In this report, we analyze Elon Musk's and Tim Cook's tweets.


<h2> Introduction </h2>
For this assignment, we are interested in the comparing tweets from **Elon Musk** and **Tim Cook**. Our main research question is the following: *How do tweets from Elon Musk and Tim Cook differ?*. Before starting the research process, we hypothesize that there would be a large difference in the sentiment of tweets; that is, we postulate that tweets from Elon will contain more extreme sentiments than those from Tim. Additionally, we expect that Elon may have more tweets with pictures while also tweeting at more sproradic and unconventional times of the day in comparison to Tim.

In sum, we have three hypotheses:

1. Elon will have more extreme sentiment in his tweets, compared to Tim
2. Tim will have fewer tweets with pictures/links, compared to Elon
3. Elon will have more sporadic tweeting patterns, compared to Tim

<h2> Methodology </h2>

In order to investigate potential differences between the tweets of Elon Musk and Tim Cook, our methodology covered the following:

- Comparing time patterns between the tweets of both accounts. The purpose for this was to gather information about the times of the day during which both accounts tweet the most or the least.  
- Comparing the number of tweets with or without pictures/links from both users The purpose for this was to understand which user tends to include pictures/links in their tweets more often. 
- Tokenizing the tweets in each account. The purpose for this was to identify differences between popular words tweeted between both accounts and to conduct a sentiment analysis on each sample of tweets.

For our predictive algorithm, we divided our data into test and train data and applied a decision tree to identify the srouces of the tweet based on the following variables:

- Whether the tweet contained pictures/links 
- The hour of the day during which the tweet was published 
- The sentiment score using the AFINN dictionary